### ISSUE TITLE
mom pokevial text

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#601]
![image](https://user-images.githubusercontent.com/73248181/227533333-96854f35-7b72-4296-86cf-31c9d0250161.png)

**Comment by Gardenette** [comment]
Who made her recharge it?
She doesn't have pokecenter technology

**Comment by Gardenette** [comment]
I fixed the text, but the item literally says it can be recharged at a pokecenter.
If we really want mom or any other form of rest healing to recharge it, we need to change the item description. I'll leave the github issue open so we can discuss

**Comment by LowEffortCoding** [comment]
I think it's a bit too much hand holding, this + pokevial + bed is way too much

**Comment by Gardenette** [comment]
I agree. We already have a healing spot in the castaneda
If anything I think route1 mom should just be lowered in level for vanilla mode and Rebalanced mode. Usually r1 mon are like levels 2 to 3 but ours are like level 5

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stygmaskyzoo** [comment]
fine by me

but i still dont know where you can heal yourself in the hacienda and i think we have to make that more clear

**Comment by Gardenette** [comment]
Fair enough. Chespin and I discussed making the hacienda pokemon a lower level as well

**Comment by Gardenette** [comment]
For now, I've removed it from Mom since it's really hand-holdy in mine and low's opinions. I think a much better approach would be nerfing the levels of the hacienda mon and possibly grunts' mon as well
